version: "3.5"

services:
  nginx:
    container_name: ngix
    build: 
      context: ./nginx
    ports:
        - "80:80"
    expose:
        - "80"
  api:
    container_name: api
    volumes:
      - ./api:/usr/src/app:rw
      - ./api/node_modules:/usr/src/app/node_modules
    build:
      context: ./api
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "4921:4921"
    expose:
      - "4921"
    networks:
      - steward-net
  mysql:
    container_name: db
    build:
      context: ./mysql
    volumes:
      - ./data/mysql/:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - steward-net
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
    ports:
      - "15671:15671"
      - "15672:15672"
    expose:
      - "15671"
      - "15672"
    networks:
      - steward-net
networks:
  steward-net:
    driver: bridge
      