version: "3.5"
services:
  nginx:
    container_name: ngix
    build: 
      context: ./nginx
    ports:
        - "80:80"
    expose:
        - "80"
    networks:
      steward_net:
        ipv4_address: 172.28.1.1
  api:
    container_name: api
    volumes:
      - ./api:/usr/src/app
      - ./api/node_modules:/usr/src/app/node_modules
    build:
      context: ./api
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "4921:4921"
    expose:
      - "4921"
    networks:
      steward_net:
        ipv4_address: 172.28.1.2
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"
      - "33061:33060"
    expose:
      - "3307"
      - "33061"
    networks:
      steward_net:
        ipv4_address: 172.28.1.3
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5672:5672"
    expose:
      - "15671"
      - "15672"
      - "5672"
    networks:
        steward_net:
          ipv4_address: 172.28.1.4
  mongo:
    container_name: mongo
    build:
      context: ./mongo
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    expose:
      - "27017"
      - "27018"
      - "27019"
    networks:
      steward_net:
        ipv4_address: 172.28.1.5
  # mongo-express:
  #   container_name: mongo_express
  #   build:
  #     context: ./mongo/mongo-express
  #   ports:
  #     - 8081:8081
  #   expose:
  #     - "8081"
  #   networks:
  #     steward_net:
  #        ipv4_address: 172.28.1.6
networks:
  steward_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
      