version: "3.5"
services:
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    volumes:
      - ./web/dist/steward:/usr/share/nginx/html
    ports:
        - "80:80"
        - "443:443"
    expose:
        - "80"
        - "443"
    networks:
      steward_net:
        ipv4_address: 172.28.1.1
  api:
    container_name: api
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
      - ./api/node_modules:/usr/src/app/node_modules
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "4921:4921"
    expose:
      - "4921"
    networks:
      steward_net:
        ipv4_address: 172.28.1.2
  web:
    container_name: web
    build:
      context: ./web
    volumes:
      - ./web:/usr/src/app
      - ./web/node_modules:/usr/src/app/node_modules
    depends_on:
      - api
      - nginx
    ports:
      - "4200:4200"
    expose:
      - "4200"
    networks:
      steward_net:
        ipv4_address: 172.28.1.3
  mysql:
    container_name: mysql
    build: 
      context: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_DATABASE: steward_wdb
    ports:
      - "3307:3306"
      - "33061:33060"
    expose:
      - "3307"
      - "33061"
    networks:
      steward_net:
        ipv4_address: 172.28.1.4
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
    restart: always
    environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5672:5672"
    expose:
      - "15671"
      - "15672"
      - "5672"
    networks:
        steward_net:
          ipv4_address: 172.28.1.5
  mongo:
    container_name: mongo
    build:
      context: ./mongo
    restart: always
    environment:
      MONGODB_ROOT_PASSWORD: admin
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin
      MONGODB_DATABASE: steward_rdb
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    expose:
      - "27017"
      - "27018"
      - "27019"
    networks:
      steward_net:
        ipv4_address: 172.28.1.6
networks:
  steward_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
      